#!/usr/bin/env bash
# Build a clean pinned Web checkout and bind deployment inputs to the generated bytes.
set -euo pipefail

script_directory="$(cd "$(dirname "$0")" && pwd -P)"
exec python3 "$script_directory/web-assets-profile.py" build "$@"
